import { lazy, Suspense, useLayoutEffect } from 'react'
import { BrowserRouter, Routes, Route, useLocation } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { hydrateQueryClient, persistQueryClient } from './utils/queryPersist'
import { Header } from './components/ui/Header'
import { PageShell } from './components/ui/PageShell'
import { SkeletonCard } from './components/ui/Skeleton'
import { ErrorBoundary } from './components/ui/ErrorBoundary'
import { HomePage } from './pages/HomePage'

// A Home é eager (é a tela de aterrissagem e pinta na hora do cache). As demais
// rotas são lazy: o bundle inicial deixa de carregar /live, /telemetria e o
// Recharts para quem só abre Home/Classificação. Cada rota baixa seu chunk só
// quando visitada — TTI bem menor, sobretudo no mobile/segunda tela.
const LivePage = lazy(() => import('./pages/LivePage').then(m => ({ default: m.LivePage })))
const StandingsPage = lazy(() => import('./pages/StandingsPage').then(m => ({ default: m.StandingsPage })))
const CalendarPage = lazy(() => import('./pages/CalendarPage').then(m => ({ default: m.CalendarPage })))
const DriverPage = lazy(() => import('./pages/DriverPage').then(m => ({ default: m.DriverPage })))
const TeamPage = lazy(() => import('./pages/TeamPage').then(m => ({ default: m.TeamPage })))
const CircuitPage = lazy(() => import('./pages/CircuitPage').then(m => ({ default: m.CircuitPage })))
const RacePage = lazy(() => import('./pages/RacePage').then(m => ({ default: m.RacePage })))
const RadioPage = lazy(() => import('./pages/RadioPage').then(m => ({ default: m.RadioPage })))
const TelemetriaPage = lazy(() => import('./pages/TelemetriaPage').then(m => ({ default: m.TelemetriaPage })))
const StatusPage = lazy(() => import('./pages/StatusPage').then(m => ({ default: m.StatusPage })))
const ComparePage = lazy(() => import('./pages/ComparePage').then(m => ({ default: m.ComparePage })))

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      staleTime: 60_000,
    },
  },
})

// Paint instantly from the last good data, then revalidate in the background.
hydrateQueryClient(queryClient)
persistQueryClient(queryClient)

// Fallback enquanto o chunk da rota baixa. Reaproveita o shell + skeleton já
// usados pelas páginas, então a troca de rota não "pisca" um layout diferente.
function RouteFallback() {
  return (
    <PageShell>
      <div className="space-y-4">
        <SkeletonCard rows={4} />
        <SkeletonCard rows={4} />
      </div>
    </PageShell>
  )
}

// React Router não reseta o scroll ao trocar de rota. Como as páginas pintam
// na hora a partir do cache persistido (altura cheia imediata), navegar de uma
// lista rolada caía no MEIO da nova página — o topo (nome/foto do piloto, etc.)
// ficava acima do viewport. Aqui forçamos o topo a cada mudança de caminho.
// useLayoutEffect + behavior:'instant' = sem flash e sem animação (o CSS tem
// scroll-behavior: smooth, que faríamos a página "subir" sozinha sem o instant).
function ScrollToTop() {
  const { pathname } = useLocation()
  useLayoutEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: 'instant' })
  }, [pathname])
  return null
}

// Última linha de defesa (ROADMAP 1.4): se uma página inteira estourar fora de
// qualquer Panel, mostramos um aviso amigável em vez de tela branca. A `key` no
// pathname remonta o boundary ao trocar de rota, então o erro some ao navegar.
function RouteErrorFallback() {
  return (
    <PageShell>
      <div className="card p-8 text-center space-y-2">
        <p className="font-display uppercase tracking-widest text-sm text-text">Algo deu errado nesta página</p>
        <p className="text-xs text-text-mute">Tente outra seção no menu — o resto do app segue funcionando.</p>
      </div>
    </PageShell>
  )
}

function RoutedBoundary({ children }) {
  const { pathname } = useLocation()
  return (
    <ErrorBoundary key={pathname} label="página" fallback={<RouteErrorFallback />}>
      {children}
    </ErrorBoundary>
  )
}

export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <BrowserRouter>
        <ScrollToTop />
        <div className="min-h-screen" style={{ background: '#0a0a0a' }}>
          <Header />
          {/* On mobile the fixed bottom nav (64px) sits over the page, so we
              reserve exactly its height + the device safe-area inset via the
              `.pb-mobile-nav` class (defined in index.css). The last line of
              every page then stops at the top edge of the menu instead of
              hiding behind it. A real CSS class is used because the Tailwind
              arbitrary value `pb-[calc(4rem+env(…))]` was NOT generated by
              Tailwind v4 (computed padding came out 0). */}
          <main className="pb-mobile-nav">
            <RoutedBoundary>
            <Suspense fallback={<RouteFallback />}>
              <Routes>
                <Route path="/" element={<HomePage />} />
                <Route path="/live" element={<LivePage />} />
                <Route path="/standings" element={<StandingsPage />} />
                <Route path="/calendar" element={<CalendarPage />} />
                <Route path="/driver/:driverId" element={<DriverPage />} />
                <Route path="/team/:constructorId" element={<TeamPage />} />
                <Route path="/circuit/:circuitId" element={<CircuitPage />} />
                <Route path="/race/:season/:round" element={<RacePage />} />
                <Route path="/radio" element={<RadioPage />} />
                <Route path="/telemetria" element={<TelemetriaPage />} />
                <Route path="/status" element={<StatusPage />} />
                <Route path="/comparar" element={<ComparePage />} />
              </Routes>
            </Suspense>
            </RoutedBoundary>
          </main>
        </div>
      </BrowserRouter>
    </QueryClientProvider>
  )
}
