import { useLayoutEffect } from 'react'
import { BrowserRouter, Routes, Route, useLocation } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { hydrateQueryClient, persistQueryClient } from './utils/queryPersist'
import { Header } from './components/ui/Header'
import { HomePage } from './pages/HomePage'
import { LivePage } from './pages/LivePage'
import { StandingsPage } from './pages/StandingsPage'
import { CalendarPage } from './pages/CalendarPage'
import { DriverPage } from './pages/DriverPage'
import { TeamPage } from './pages/TeamPage'
import { CircuitPage } from './pages/CircuitPage'
import { RacePage } from './pages/RacePage'
import { RadioPage } from './pages/RadioPage'
import { TelemetriaPage } from './pages/TelemetriaPage'

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      staleTime: 60_000,
    },
  },
})

// Paint instantly from the last good data, then revalidate in the background.
hydrateQueryClient(queryClient)
persistQueryClient(queryClient)

// React Router não reseta o scroll ao trocar de rota. Como as páginas pintam
// na hora a partir do cache persistido (altura cheia imediata), navegar de uma
// lista rolada caía no MEIO da nova página — o topo (nome/foto do piloto, etc.)
// ficava acima do viewport. Aqui forçamos o topo a cada mudança de caminho.
// useLayoutEffect + behavior:'instant' = sem flash e sem animação (o CSS tem
// scroll-behavior: smooth, que faríamos a página "subir" sozinha sem o instant).
function ScrollToTop() {
  const { pathname } = useLocation()
  useLayoutEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: 'instant' })
  }, [pathname])
  return null
}

export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <BrowserRouter>
        <ScrollToTop />
        <div className="min-h-screen" style={{ background: '#0a0a0a' }}>
          <Header />
          {/* On mobile the fixed bottom nav (64px) sits over the page, so we
              reserve exactly its height + the device safe-area inset via the
              `.pb-mobile-nav` class (defined in index.css). The last line of
              every page then stops at the top edge of the menu instead of
              hiding behind it. A real CSS class is used because the Tailwind
              arbitrary value `pb-[calc(4rem+env(…))]` was NOT generated by
              Tailwind v4 (computed padding came out 0). */}
          <main className="pb-mobile-nav">
            <Routes>
              <Route path="/" element={<HomePage />} />
              <Route path="/live" element={<LivePage />} />
              <Route path="/standings" element={<StandingsPage />} />
              <Route path="/calendar" element={<CalendarPage />} />
              <Route path="/driver/:driverId" element={<DriverPage />} />
              <Route path="/team/:constructorId" element={<TeamPage />} />
              <Route path="/circuit/:circuitId" element={<CircuitPage />} />
              <Route path="/race/:season/:round" element={<RacePage />} />
              <Route path="/radio" element={<RadioPage />} />
              <Route path="/telemetria" element={<TelemetriaPage />} />
            </Routes>
          </main>
        </div>
      </BrowserRouter>
    </QueryClientProvider>
  )
}
